def dichotomie(tab, x):
    """
    tab : tableau d’entiers trié dans l’ordre croissant
    x : nombre entier
    La fonction renvoie True si tab contient x et False sinon
    """
    debut = ...
    fin = ...
    while debut <= fin:
        milieu = ...
        if x == tab[milieu]:
            return ...
        if x > ...:
            debut = ...
        else:
            fin = ...
    return ...
